spring:
  datasource:
    url: jdbc:h2:mem:maindb
  liquibase:
    enabled: true

#  h2: # настройка для открытия консоли в веб-интерфейсе
#    console:
#      path: /h2-console   # URL консоли в веб-интерфейсе
#      settings:
#        web-allow-others: true
