spring:
  datasource:
    url: jdbc:h2:mem:maindb
  liquibase:
    enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: false
logging:
  level:
    root: error